version: '3.0'
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  db:
    container_name: postgres
    restart: always
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: gameai
      POSTGRES_PASSWORD: gameai
      POSTGRES_DB: gamedb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:

volumes:
  db-data: